repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v2.3.0
      hooks:
      -   id: check-yaml
      -   id: end-of-file-fixer
          exclude: ^test_files
      -   id: trailing-whitespace
      -   id: flake8
          args: ['--max-complexity=30']
    - repo: https://github.com/ambv/black
      rev: stable
      hooks:
      - id: black
        exclude: ^emmet-old
