name: testing

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 6
      matrix:
        package: ["emmet-core"]

    steps:
      - uses: actions/checkout@v1

      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ${{ matrix.package }}/requirements.txt
          pip install -r requirements-testing.txt

      - name: Lint with pycodestyle
        run: pycodestyle ${{ matrix.package }}

      - name: Lint with mypy
        run: mypy --namespace-package ${{ matrix.package }}

      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 --count --show-source --statistics ${{ matrix.package }}
          # exit-zero treats all errors as warnings.
          flake8 --count --exit-zero --max-complexity=20 --statistics ${{ matrix.package }}
