name: testing

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 6
      matrix:
        package: ["emmet-core", "emmet-builders"]

    steps:
      - uses: actions/checkout@v2.3.4

      - name: Set up Python 3.7
        uses: actions/setup-python@v2.2.2
        with:
          python-version: 3.7

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-testing.txt

      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 --count --show-source --statistics ${{ matrix.package }}
          # exit-zero treats all errors as warnings.
          flake8 --count --exit-zero --max-complexity=20 --statistics ${{ matrix.package }}

  test:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 6
      matrix:
        package: ["emmet-core", "emmet-builders"]

    steps:
      - uses: actions/checkout@v2.3.4

      - name: Set up Python 3.7
        uses: actions/setup-python@v2.2.2
        with:
          python-version: 3.7

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-testing.txt
          pip install -r requirements.txt

      - name: Install Packages
        run: |
          pip install -e emmet-core
          pip install -e emmet-builders

      - name: Lint with mypy
        run: mypy --namespace-package ${{ matrix.package }}/emmet

      - name: Test with pytest
        run: |
          pytest --cov=emmet --cov-report=xml tests/${{ matrix.package }}

      - uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml

  docs:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.3.4

    - uses: actions/setup-python@v2.2.2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -e emmet-core/
        pip install -e emmet-builders/
        pip install -r requirements-docs.txt

    - name: Build
      run: mkdocs build

  merge-deps:
    needs:
      - lint
      - test
      - docs
    runs-on: ubuntu-latest
    steps:
      - name: Merge me!
        uses: ridedott/merge-me-action@master
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  auto-gen-release:
    needs:
      - lint
      - test
      - docs
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.EMMET_SEMVER_BUMP_TOKEN }}
    steps:
      - uses: rymndhng/release-on-push-action@v0.20.0
        with:
          bump_version_scheme: norelease
