name: testing

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e emmet-core

    - name: Lint with pycodestyle
      run: |
        pip install pycodestyle
        pycodestyle emmet-core/emmet

    - name: Lint with mypy
      run: |
        pip install mypy
        mypy --namespace-package emmet-core/emmet

    - name: Lint with flake8
      run: |
        pip install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 --count --show-source --statistics emmet-core
        # exit-zero treats all errors as warnings.
        flake8 --count --exit-zero --max-complexity=20 --statistics emmet-core
